services:
  filebrowser:
    image: hurlenko/filebrowser
    user: "1000:1000"
    ports:
      - 8095:8080
    volumes:
      - /data:/data
      - /data/filebrowser:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: always
