services:
  obsidian:
    image: lscr.io/linuxserver/obsidian:latest
    container_name: obsidian
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000s
      - TZ=Etc/UTC
    volumes:
      - /data/obisdian/config:/config
    ports:
      - 3003:3000
      - 3004:3001
    shm_size: "1gb"
    restart: unless-stopped
