services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - AUTO_UPDATE=true
      - RUN_OPTS=
    volumes:
      - /data/jackett:/config
      - /data/media/disk0/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
