services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /data/radarr:/config
      - /data/media/disk1/movies:/movies
      - /data/media/disk1/download:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Eurpose/Warsaw
    volumes:
      - /data/sonarr:/config
      - /data/media/disk1/tv:/tv
      - /data/media/disk1/download:/downloads
    ports:
      - 8989:8989

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /data/qbittorent/appdata/config:/config
      - /data/media/disk1/download:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    volumes:
      - /data/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    network_mode: "host"
    group_add:
      - "993"
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /data/jellyfin/config:/config
      - /data/jellyfin/cache:/cache
      - type: bind
        source: /data/media
        target: /media
        read_only: true
    restart: "unless-stopped"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - AUTO_UPDATE=true
      - RUN_OPTS=
    volumes:
      - /data/jackett:/config
      - /data/media/disk0/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
