esphome:
  name: test
  friendly_name: test

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "zpQpC8E8BwYaeSfaL7pd42bs64AzlDXV+qNIoC9d/zA="

ota:
  - platform: esphome
    password: "a690d4628153b223f18ad5bd162b3bf5"

wifi:
  ssid: "UPC1302310"
  password: "zvsAuxdwkhz8"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "h4E7aTdQauWf"

one_wire:
  - platform: gpio
    pin: GPIO4

sensor:
  - platform: dallas_temp
    name: temperature

captive_portal:
    