services:

  couchdb:
    image: couchdb:3.3.3
    restart: always
    ports:
     - 5984:5984
    volumes:
     - /data/couchdb/data:/opt/couchdb/data
     - /data/couchdb/etc/local.d:/opt/couchdb/etc/local.d
    environment:
      COUCHDB_USER: ${USER}
      COUCHDB_PASSWORD: ${PASSWORD}
